module

public import SpytialLeanMetatheory.LeanExprMeaning
public meta import SpytialLean.InContext

public section

/-!
# One relational meaning for production tuples

The production theorems must not quantify over an unrelated `GroundInstance`.
This module defines one relation-truth judgment generated by the two supported
sources: checked structural origins and checked proved origins. It then
constructs the ground instance from that judgment. Individual tuple
realizations contain only syntactic, typing, and atom-correspondence evidence.
-/

namespace SpytialLean.Metatheory

open Lean SpytialLean

universe u v

namespace LeanExprMeaning

/-- A semantic instance made from expression-backed tuples. -/
@[expose] public def instanceOfTuples {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    (meaning : LeanExprMeaning World context)
    (tuples : List (RelationalTuple meaning.signature (ExprAtom meaning))) :
    SemanticInstance context meaning.signature meaning.Carrier :=
  SemanticInstance.ofTuples context meaning.signature meaning.Carrier
    (ExprAtom meaning) ExprAtom.denote tuples

end LeanExprMeaning

/-- Unfold the expression-backed signature at a relation symbol. -/
@[expose] public def exprRelation {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    {meaning : LeanExprMeaning World context}
    (relation : meaning.signature.Relation) : LeanExprMeaning.ExprRelation meaning :=
  relation

/-- The production atom identifiers used by one expression-backed tuple. -/
@[expose] public def exprTupleAtomIds {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    {meaning : LeanExprMeaning World context}
    (tuple : RelationalTuple meaning.signature (LeanExprMeaning.ExprAtom meaning)) :
    List String :=
  tuple.atoms.map fun atom => atom.value.id

/-- The checked Lean terms denoted by an expression-backed tuple. -/
@[expose] public def exprTupleTerms {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    {meaning : LeanExprMeaning World context}
    (tuple : RelationalTuple meaning.signature (LeanExprMeaning.ExprAtom meaning)) :
    List Expr :=
  tuple.atoms.map fun atom => atom.value.term.expression

/-- Syntactic and typed correspondence between one checked proof origin and
    one semantic tuple. This structure contains no tuple-truth assumption. -/
public structure ProvedTupleRealization {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    (meaning : LeanExprMeaning World context) (origin : CheckedProvedOrigin)
    (tuple : RelationalTuple meaning.signature (LeanExprMeaning.ExprAtom meaning)) where
  relation_name : (exprRelation tuple.relation).name = origin.relation
  relation_head : (exprRelation tuple.relation).head =
    Quotient.mk meaning.defEq origin.head
  relation_parameters : (exprRelation tuple.relation).parameters =
    origin.parameters.toList.map fun parameter => Quotient.mk meaning.defEq parameter
  column_types : (exprRelation tuple.relation).columns =
    origin.columns.types.map fun type => Quotient.mk meaning.defEq type
  atom_ids : exprTupleAtomIds tuple = origin.atoms.toList
  atom_terms : exprTupleTerms tuple = origin.terms.toList
  proof_checked : meaning.proofChecks origin.proposition origin.proof

/-- Syntactic and typed correspondence between one checked constructor-field
    or projection origin and one semantic tuple. -/
public structure StructuralTupleRealization {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    (meaning : LeanExprMeaning World context) (origin : CheckedStructuralOrigin)
    (tuple : RelationalTuple meaning.signature (LeanExprMeaning.ExprAtom meaning)) where
  relation_name : (exprRelation tuple.relation).name = origin.relation
  column_types : (exprRelation tuple.relation).columns =
    origin.columns.types.map fun type => Quotient.mk meaning.defEq type
  atom_ids : exprTupleAtomIds tuple = origin.emission.tuple.atoms.toList
  atom_terms : exprTupleTerms tuple = origin.terms.toList

/-- Truth in the supported production relation semantics. A tuple is true when
    it is the denotation of a checked structural origin, or when it is the
    denotation of a checked proved origin whose proposition is true. -/
public inductive ProductionTupleHolds {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    (meaning : LeanExprMeaning World context) (world : World) :
    (relation : meaning.signature.Relation) →
      TypedTuple meaning.Carrier (meaning.signature.columns relation) → Prop where
  | proved {origin tuple} (realization : ProvedTupleRealization meaning origin tuple)
      (compatible : context world)
      (propositionHolds : meaning.proposition origin.proposition world) :
      ProductionTupleHolds meaning world tuple.relation
        (tuple.entries.map fun atom =>
          LeanExprMeaning.ExprAtom.denote atom world compatible)
  | structural {origin tuple}
      (realization : StructuralTupleRealization meaning origin tuple)
      (compatible : context world) :
      ProductionTupleHolds meaning world tuple.relation
        (tuple.entries.map fun atom =>
          LeanExprMeaning.ExprAtom.denote atom world compatible)

namespace ProductionTupleHolds

/-- The ground instance generated by checked production origins. -/
@[expose] public def ground {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    (meaning : LeanExprMeaning World context) :
    World → GroundInstance meaning.signature meaning.Carrier :=
  fun world => { holds := ProductionTupleHolds meaning world }

/-- A true proposition makes its represented proof-derived tuple true in the
    production ground instance. -/
public theorem provedTupleHolds {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    {meaning : LeanExprMeaning World context}
    {tuples : List (RelationalTuple meaning.signature
      (LeanExprMeaning.ExprAtom meaning))}
    {origin : CheckedProvedOrigin}
    {tuple : RelationalTuple meaning.signature (LeanExprMeaning.ExprAtom meaning)}
    (realization : ProvedTupleRealization meaning origin tuple)
    (world : World) (compatible : context world)
    (propositionHolds : meaning.proposition origin.proposition world) :
    (meaning.instanceOfTuples tuples).TupleHolds (ground meaning) tuple world compatible := by
  exact .proved realization compatible propositionHolds

/-- Rechecking the retained Lean proof is enough to establish the represented
    tuple in every compatible world. -/
public theorem checkedProvedTupleHolds {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    {meaning : LeanExprMeaning World context}
    {tuples : List (RelationalTuple meaning.signature
      (LeanExprMeaning.ExprAtom meaning))}
    {origin : CheckedProvedOrigin}
    {tuple : RelationalTuple meaning.signature (LeanExprMeaning.ExprAtom meaning)}
    (realization : ProvedTupleRealization meaning origin tuple)
    (world : World) (compatible : context world) :
    (meaning.instanceOfTuples tuples).TupleHolds (ground meaning) tuple world compatible := by
  apply provedTupleHolds realization world compatible
  exact meaning.proofChecks_sound realization.proof_checked world compatible

/-- Every represented checked structural origin is true in the same production
    ground instance. -/
public theorem structuralTupleHolds {World : Type u}
    {context : Iykyk.Metatheory.Context World}
    {meaning : LeanExprMeaning World context}
    {tuples : List (RelationalTuple meaning.signature
      (LeanExprMeaning.ExprAtom meaning))}
    {origin : CheckedStructuralOrigin}
    {tuple : RelationalTuple meaning.signature (LeanExprMeaning.ExprAtom meaning)}
    (realization : StructuralTupleRealization meaning origin tuple)
    (world : World) (compatible : context world) :
    (meaning.instanceOfTuples tuples).TupleHolds (ground meaning) tuple world compatible := by
  exact .structural realization compatible

end ProductionTupleHolds

end SpytialLean.Metatheory
