module

public import SpytialLean.StructuralExposure
public meta import SpytialLean.TypeShape
public meta import Lean.Elab.Deriving.Basic
public meta import Lean.Elab.Deriving.Util

namespace SpytialLean.SpytialReify.Deriving

open Lean Meta Elab Command Term
open Lean.Elab.Deriving
open Lean.Parser.Term

public meta structure FieldPlan where
  type : Term
  relation : String
  recursive : Bool
  deriving Inhabited

public meta structure CtorPlan where
  name : Name
  label : String
  numParams : Nat
  fields : Array FieldPlan

public meta structure Plan where
  declName : Name
  indVal : InductiveVal
  argNames : Array Name
  ctors : Array CtorPlan

private meta structure DecoderNames where
  reifyAt : Name
  representsAt : Name
  complete : Name
  structuralInstance : Name

/-- Type name to the checker generated by `deriving SpytialReify`. -/
public meta initialize derivedRepresentsExt :
    SimplePersistentEnvExtension (Name × Name) (NameMap Name) ←
  registerSimplePersistentEnvExtension {
    addEntryFn := fun state (typeName, checker) => state.insert typeName checker
    addImportedFn := fun arrays =>
      arrays.foldl
        (fun state entries => entries.foldl
          (fun state (typeName, checker) => state.insert typeName checker) state)
        {}
  }

/-- Find the structural checker generated for a derived decoder. -/
public meta def derivedRepresentsName? (environment : Environment) (typeName : Name) :
    Option Name :=
  derivedRepresentsExt.getState environment |>.find? typeName

private meta def unsupported (declName : Name) (message : MessageData) : TermElabM α :=
  throwError "cannot derive `SpytialReify` for `{.ofConstName declName}`: {message}"

/-- Render a first-order field type in generated decoder code. Only datatype parameters may occur
free; dependencies on earlier constructor fields require dependent reconstruction. -/
private meta partial def renderFieldType (declName : Name)
    (params : Array (FVarId × Ident)) : Expr → TermElabM Term
  | .fvar id =>
    match params.findSome? (fun (param, name) => if param == id then some name else none) with
    | some name => pure name
    | none => unsupported declName m!"a constructor field depends on an earlier field"
  | .const name _ => `(@$(mkCIdent name):ident)
  | .lit (.natVal value) => pure (quote value)
  | .lit (.strVal value) => pure (quote value)
  | expression@(.app ..) => do
    let arguments ← expression.getAppArgs.mapM (renderFieldType declName params)
    match expression.getAppFn with
    | .const name _ => `(@$(mkCIdent name):ident $arguments:term*)
    | .fvar id =>
      let function ← renderFieldType declName params (.fvar id)
      `($function $arguments:term*)
    | function => unsupported declName m!"unsupported field type head{indentExpr function}"
  | .mdata _ expression => renderFieldType declName params expression
  | expression => unsupported declName m!"unsupported field type{indentExpr expression}"

public meta def mkPlan (declName : Name) : TermElabM Plan := do
  let indVal ← getConstInfoInduct declName
  unless indVal.all.length == 1 do
    unsupported declName m!"mutually recursive decoders are not yet supported"
  unless indVal.numIndices == 0 do
    unsupported declName m!"indexed inductive families require dependent reconstruction"
  if indVal.isNested then
    unsupported declName m!"nested recursion is not yet supported"
  let argNames ← mkInductArgNames indVal
  let mut ctors := #[]
  for constructor in indVal.ctors do
    let info ← getConstInfoCtor constructor
    let binderNames := ctorDataBinderNames info
    let fields ← forallTelescopeReducing info.type fun variables _ => do
      let constructorParams := variables.extract 0 info.numParams
      let params := constructorParams.mapIdx fun index parameter =>
        (parameter.fvarId!, mkIdent argNames[index]!)
      let mut fields := #[]
      for index in [:info.numFields] do
        let field := variables[info.numParams + index]!
        let declaration ← field.fvarId!.getDecl
        let type ← whnf declaration.type
        if ← isProp type then
          unsupported declName m!"proof fields require proof reconstruction"
        if type.isSort then
          unsupported declName m!"type-valued fields are not supported"
        if type.isForall then
          unsupported declName m!"function fields are not supported"
        let recursive := type.isAppOf declName
        if type.getUsedConstants.contains declName && !recursive then
          unsupported declName m!"nested recursion is not yet supported"
        if recursive then
          let arguments := type.getAppArgs
          unless arguments.size == constructorParams.size do
            unsupported declName m!"non-regular recursive occurrence"
          for argument in arguments, parameter in constructorParams do
            unless ← isDefEq argument parameter do
              unsupported declName
                m!"recursive occurrences must use the datatype's parameters unchanged"
        let relation := fieldRelName (shortName constructor) binderNames index
        -- Relation tuples are unordered: one owner and one relation name cannot encode which
        -- constructor position supplied each of two distinct targets.
        if fields.any fun field => field.relation == relation then
          unsupported declName
            m!"constructor `{shortName constructor}` maps more than one field to \
              relation `{relation}`"
        fields := fields.push {
          type := ← renderFieldType declName params type
          relation
          recursive
        }
      return fields
    ctors := ctors.push {
      name := constructor
      label := shortName constructor
      numParams := info.numParams
      fields
    }
  return { declName, indVal, argNames, ctors }

private meta def mkNames (plan : Plan) : TermElabM DecoderNames := do
  let reifyInstance ← mkInstName ``SpytialReify plan.declName
  return {
    reifyAt := reifyInstance.appendAfter "_decodeAt"
    representsAt := reifyInstance.appendAfter "_representsAt"
    complete := reifyInstance.appendAfter "_decodeAt_complete"
    structuralInstance := reifyInstance.appendAfter "_structural"
  }

open TSyntax.Compat in
private meta def mkBinders (plan : Plan) (includeStructural : Bool := false) :
    TermElabM (Array (TSyntax ``bracketedBinder)) := do
  let mut binders := #[]
  for binder in ← mkImplicitBinders plan.argNames do
    binders := binders.push binder
  for binder in ← mkInstImplicitBinders ``SpytialReify plan.indVal plan.argNames do
    binders := binders.push binder
  if includeStructural then
    for binder in ←
        mkInstImplicitBinders ``SpytialLean.StructuralReification plan.indVal plan.argNames do
      binders := binders.push binder
  return binders

private meta def mkCtorBody (names : DecoderNames) (constructor : CtorPlan)
    (datum root fuel : Ident) : TermElabM Term := do
  let mut fields : Array Ident := #[]
  for _ in constructor.fields do
    fields := fields.push (mkIdent (← mkFreshUserName `field))
  -- Constructor fields include implicit and instance binders. Apply every decoded field
  -- explicitly so elaboration cannot infer or synthesize a different value for a hidden field.
  let mut arguments : Array Term := #[]
  for _ in [:constructor.numParams] do
    arguments := arguments.push (← `(_))
  arguments := arguments ++ fields.map (fun field => ⟨field.raw⟩)
  let value ← `(@$(mkCIdent constructor.name):ident $arguments:term*)
  let mut body ← `(Except.ok $value)
  for index in (List.range constructor.fields.size).reverse do
    let field := fields[index]!
    let decodeError := mkIdent (← mkFreshUserName `error)
    let fieldPlan := constructor.fields[index]!
    let child := mkIdent (← mkFreshUserName `child)
    let decodeChild ← if fieldPlan.recursive then
      `(fun $child:ident => $(mkIdent names.reifyAt) $datum:ident $child:ident $fuel:ident)
    else
      `(fun $child:ident => SpytialLean.SpytialReify.decodeAt (α := $(fieldPlan.type))
        $datum:ident $child:ident $fuel:ident)
    let decode ← `(SpytialLean.JsonDataInstance.decodeChildWith
      $datum:ident $root:ident $(quote fieldPlan.relation) $decodeChild:term)
    body ← `(match $decode:term with
      | Except.error $decodeError:ident => Except.error $decodeError:ident
      | Except.ok $field:ident => $body:term)
  return body

open TSyntax.Compat in
private meta def mkDecoder (plan : Plan) (names : DecoderNames) :
    TermElabM (TSyntax `command) := do
  let indApp ← mkInductiveApp plan.indVal plan.argNames
  let binders ← mkBinders plan
  let datum := mkIdent (← mkFreshUserName `datum)
  let root := mkIdent (← mkFreshUserName `root)
  let fuel := mkIdent (← mkFreshUserName `fuel)
  let nextFuel := mkIdent (← mkFreshUserName `fuel)
  let atom := mkIdent (← mkFreshUserName `atom)
  let error := mkIdent (← mkFreshUserName `error)

  let mut labelAlts : Array (TSyntax ``matchAlt) := #[]
  for constructor in plan.ctors do
    let body ← mkCtorBody names constructor datum root nextFuel
    labelAlts := labelAlts.push
      (← `(matchAltExpr| | $(quote constructor.label) => $body:term))
  labelAlts := labelAlts.push
    (← `(matchAltExpr| | _ => SpytialLean.reifyError "reify: unknown constructor"))
  let labelMatch ← `(match ($atom:ident).label with $labelAlts:matchAlt*)
  let atomMatch ← `(match SpytialLean.JsonDataInstance.expectAtom
      $datum:ident $root:ident $(quote (shortName plan.declName)) with
    | Except.error $error:ident => Except.error $error:ident
    | Except.ok $atom:ident => $labelMatch:term)
  let body ← `(match $fuel:ident with
    | 0 => SpytialLean.reifyError "reify: decoder fuel exhausted"
    | $nextFuel:ident + 1 => $atomMatch:term)
  if plan.indVal.isRec then
    `(def $(mkIdent names.reifyAt):ident $binders:bracketedBinder*
        ($datum:ident : SpytialLean.JsonDataInstance) ($root:ident : String) ($fuel:ident : Nat) :
        Except SpytialLean.ReifyError $indApp := $body:term
      termination_by $fuel:ident)
  else
    `(def $(mkIdent names.reifyAt):ident $binders:bracketedBinder*
        ($datum:ident : SpytialLean.JsonDataInstance) ($root:ident : String) ($fuel:ident : Nat) :
        Except SpytialLean.ReifyError $indApp := $body:term)

private meta def mkFieldRepresentation (names : DecoderNames) (fieldPlan : FieldPlan)
    (datum root fuel field : Ident) : TermElabM Term := do
  let child := mkIdent (← mkFreshUserName `child)
  let value := mkIdent (← mkFreshUserName `value)
  let represents ← if fieldPlan.recursive then
    `(fun $child:ident $value:ident =>
      $(mkIdent names.representsAt) $datum:ident $child:ident $fuel:ident $value:ident)
  else
    `(fun $child:ident $value:ident =>
      SpytialLean.StructuralReification.representsAt (α := $(fieldPlan.type))
        $datum:ident $child:ident $fuel:ident $value:ident)
  `(SpytialLean.JsonDataInstance.childRepresentsWith
    $datum:ident $root:ident $(quote fieldPlan.relation) $represents:term $field:ident)

private meta def mkCtorRepresentation (names : DecoderNames) (plan : Plan)
    (constructor : CtorPlan) (datum root fuel : Ident) : TermElabM (TSyntax ``matchAlt) := do
  let mut fields : Array Ident := #[]
  for _ in constructor.fields do
    fields := fields.push (mkIdent (← mkFreshUserName `field))
  let mut fieldChecks ← `(true)
  for index in (List.range constructor.fields.size).reverse do
    let check ← mkFieldRepresentation names constructor.fields[index]!
      datum root fuel fields[index]!
    fieldChecks ← `($check:term && $fieldChecks:term)
  let body ← `(SpytialLean.JsonDataInstance.constructorRepresents
    $datum:ident $root:ident $(quote (shortName plan.declName))
      $(quote constructor.label) $fieldChecks:term)
  let mut arguments : Array Term := #[]
  for _ in [:constructor.numParams] do
    arguments := arguments.push (← `(_))
  arguments := arguments ++ fields.map (fun field => ⟨field.raw⟩)
  `(matchAltExpr| | @$(mkCIdent constructor.name):ident $arguments:term* => $body:term)

open TSyntax.Compat in
private meta def mkRepresentsAt (plan : Plan) (names : DecoderNames) :
    TermElabM (TSyntax `command) := do
  let indApp ← mkInductiveApp plan.indVal plan.argNames
  let binders ← mkBinders plan true
  let datum := mkIdent (← mkFreshUserName `datum)
  let root := mkIdent (← mkFreshUserName `root)
  let fuel := mkIdent (← mkFreshUserName `fuel)
  let nextFuel := mkIdent (← mkFreshUserName `fuel)
  let value := mkIdent (← mkFreshUserName `value)
  let mut alternatives := #[]
  for constructor in plan.ctors do
    alternatives := alternatives.push
      (← mkCtorRepresentation names plan constructor datum root nextFuel)
  let valueMatch ← `(match $value:ident with $alternatives:matchAlt*)
  let body ← `(match $fuel:ident with
    | 0 => false
    | $nextFuel:ident + 1 => $valueMatch:term)
  if plan.indVal.isRec then
    `(@[expose] def $(mkIdent names.representsAt):ident $binders:bracketedBinder*
        ($datum:ident : SpytialLean.JsonDataInstance) ($root:ident : String)
        ($fuel:ident : Nat) ($value:ident : $indApp) : Bool := $body:term
      termination_by $fuel:ident)
  else
    `(@[expose] def $(mkIdent names.representsAt):ident $binders:bracketedBinder*
        ($datum:ident : SpytialLean.JsonDataInstance) ($root:ident : String)
        ($fuel:ident : Nat) ($value:ident : $indApp) : Bool := $body:term)

private meta def andComponent (conjunction : Ident) (index : Nat) : TermElabM Term := do
  let mut component : Term := conjunction
  for _ in [:index] do
    component ← `(($component:term).2)
  `(($component:term).1)

private abbrev SimpArg := TSyntax
  [`Lean.Parser.Tactic.simpStar, `Lean.Parser.Tactic.simpErase, `Lean.Parser.Tactic.simpLemma]

private meta def mkSimpArg (term : Term) : TermElabM SimpArg :=
  `(Lean.Parser.Tactic.simpLemma| $term:term)

private meta def mkFieldDecoder (names : DecoderNames) (fieldPlan : FieldPlan)
    (datum fuel : Ident) : TermElabM Term := do
  let child := mkIdent (← mkFreshUserName `child)
  if fieldPlan.recursive then
    `(fun $child:ident => $(mkIdent names.reifyAt) $datum:ident $child:ident $fuel:ident)
  else
    `(fun $child:ident => SpytialLean.SpytialReify.decodeAt (α := $(fieldPlan.type))
      $datum:ident $child:ident $fuel:ident)

private meta def mkFieldComplete (fieldPlan : FieldPlan)
    (datum field inductionHypothesis childHypothesis : Ident) : TermElabM Term := do
  let child := mkIdent (← mkFreshUserName `child)
  if fieldPlan.recursive then
    `(fun $child:ident $childHypothesis:ident =>
      $inductionHypothesis:ident $datum:ident $child:ident $field:ident $childHypothesis:ident)
  else
    `(fun _ $childHypothesis:ident =>
      SpytialLean.StructuralReification.decodeAt_complete (α := $(fieldPlan.type))
        $childHypothesis:ident)

private meta def mkCtorCompleteAlt (names : DecoderNames) (plan : Plan)
    (constructor : CtorPlan) (datum root fuel inductionHypothesis hypothesis : Ident) :
    TermElabM (TSyntax ``Lean.Parser.Tactic.inductionAlt) := do
  let mut fields : Array Ident := #[]
  for _ in constructor.fields do
    fields := fields.push (mkIdent (← mkFreshUserName `field))
  let atomEquation := mkIdent (← mkFreshUserName `atomEquation)
  let atom := mkIdent (← mkFreshUserName `atom)
  let error := mkIdent (← mkFreshUserName `error)
  let labelProof ← andComponent hypothesis 0
  let mut decodedFields : Array Ident := #[]
  for _ in constructor.fields do
    decodedFields := decodedFields.push (mkIdent (← mkFreshUserName `decodedField))

  let mut fieldTactics : Array (TSyntax `tactic) := #[]
  for index in List.range constructor.fields.size do
    let fieldPlan := constructor.fields[index]!
    let field := fields[index]!
    let decoded := decodedFields[index]!
    let decoder ← mkFieldDecoder names fieldPlan datum fuel
    let decode ← `(SpytialLean.JsonDataInstance.decodeChildWith
      $datum:ident $root:ident $(quote fieldPlan.relation) $decoder:term)
    let childHypothesis := mkIdent (← mkFreshUserName `childHypothesis)
    let complete ← mkFieldComplete fieldPlan datum field inductionHypothesis
      childHypothesis
    let fieldEvidence ← andComponent hypothesis (index + 1)
    let proof ← `(SpytialLean.JsonDataInstance.decodeChildWith_complete
      $complete:term $fieldEvidence:term)
    let haveField ← `(tactic| have $decoded:ident :
      $decode:term = Except.ok $field:ident := $proof:term)
    fieldTactics := fieldTactics.push haveField

  let caseName := mkIdent constructor.name.getString!.toName
  let currentNamespace ← getCurrNamespace
  let representsAt := mkIdentFrom (← getRef) (currentNamespace ++ names.representsAt)
  let reifyAt := mkIdentFrom (← getRef) (currentNamespace ++ names.reifyAt)
  let representsAtArg ← mkSimpArg representsAt
  let mut decoderArgs : Array SimpArg := #[
    ← mkSimpArg reifyAt, ← mkSimpArg atomEquation, ← mkSimpArg labelProof
  ]
  for decodedField in decodedFields do
    decoderArgs := decoderArgs.push (← mkSimpArg decodedField)
  let constructorArg ←
    mkSimpArg (mkIdent ``SpytialLean.JsonDataInstance.constructorRepresents)
  let atomEquationArg ← mkSimpArg atomEquation
  if fieldTactics.isEmpty then
    `(Lean.Parser.Tactic.inductionAlt| | @$caseName:ident $fields:ident* =>
      cases $atomEquation:ident : SpytialLean.JsonDataInstance.expectAtom
          $datum:ident $root:ident $(quote (shortName plan.declName)) with
      | error $error:ident =>
          simp [$representsAtArg, $constructorArg, $atomEquationArg] at $hypothesis:ident
      | ok $atom:ident =>
          simp only [$representsAtArg, $constructorArg, $atomEquationArg,
            Bool.and_eq_true, beq_iff_eq] at $hypothesis:ident
          simp [$decoderArgs,*])
  else
    `(Lean.Parser.Tactic.inductionAlt| | @$caseName:ident $fields:ident* =>
      cases $atomEquation:ident : SpytialLean.JsonDataInstance.expectAtom
          $datum:ident $root:ident $(quote (shortName plan.declName)) with
      | error $error:ident =>
          simp [$representsAtArg, $constructorArg, $atomEquationArg] at $hypothesis:ident
      | ok $atom:ident =>
          simp only [$representsAtArg, $constructorArg, $atomEquationArg,
            Bool.and_eq_true, beq_iff_eq] at $hypothesis:ident
          $fieldTactics:tactic*
          simp [$decoderArgs,*])

open TSyntax.Compat in
private meta def mkComplete (plan : Plan) (names : DecoderNames) :
    TermElabM (TSyntax `command) := do
  let indApp ← mkInductiveApp plan.indVal plan.argNames
  let binders ← mkBinders plan true
  let datum := mkIdent (← mkFreshUserName `datum)
  let root := mkIdent (← mkFreshUserName `root)
  let fuel := mkIdent (← mkFreshUserName `fuel)
  let nextFuel := mkIdent (← mkFreshUserName `fuel)
  let value := mkIdent (← mkFreshUserName `value)
  let hypothesis := mkIdent (← mkFreshUserName `represents)
  let inductionHypothesis := mkIdent (← mkFreshUserName `inductionHypothesis)
  let representsAt := mkIdentFrom (← getRef) ((← getCurrNamespace) ++ names.representsAt)
  let mut constructorAlts := #[]
  for constructor in plan.ctors do
    constructorAlts := constructorAlts.push
      (← mkCtorCompleteAlt names plan constructor datum root nextFuel
        inductionHypothesis hypothesis)
  let proof ← if plan.indVal.isRec then
    `(by
      intro $datum:ident $root:ident $fuel:ident
      induction $fuel:ident generalizing $datum:ident $root:ident with
      | zero =>
          intro $value:ident $hypothesis:ident
          simp [$representsAt:ident] at $hypothesis:ident
      | succ $nextFuel:ident $inductionHypothesis:ident =>
          intro $value:ident $hypothesis:ident
          cases $value:ident with $constructorAlts:inductionAlt*)
  else
    `(by
      intro $datum:ident $root:ident $fuel:ident $value:ident $hypothesis:ident
      cases $fuel:ident with
      | zero => simp [$representsAt:ident] at $hypothesis:ident
      | succ $nextFuel:ident =>
          cases $value:ident with $constructorAlts:inductionAlt*)
  `(theorem $(mkIdent names.complete):ident $binders:bracketedBinder* :
      ∀ ($datum:ident : SpytialLean.JsonDataInstance) ($root:ident : String)
          ($fuel:ident : Nat) ($value:ident : $indApp),
        $(mkIdent names.representsAt) $datum:ident $root:ident $fuel:ident $value:ident = true →
          $(mkIdent names.reifyAt) $datum:ident $root:ident $fuel:ident = Except.ok $value:ident :=
      $proof:term)

open TSyntax.Compat in
private meta def mkInstance (plan : Plan) (names : DecoderNames) :
    TermElabM (TSyntax `command) := do
  let indApp ← mkInductiveApp plan.indVal plan.argNames
  let binders ← mkBinders plan
  let instanceName ← mkInstName ``SpytialReify plan.declName
  `(instance $(mkIdent instanceName):ident $binders:bracketedBinder* :
      SpytialLean.SpytialReify $indApp where
    reifyAt := $(mkIdent names.reifyAt))

open TSyntax.Compat in
private meta def mkStructuralInstance (plan : Plan) (names : DecoderNames) :
    TermElabM (TSyntax `command) := do
  let indApp ← mkInductiveApp plan.indVal plan.argNames
  let binders ← mkBinders plan true
  `(instance $(mkIdent names.structuralInstance):ident $binders:bracketedBinder* :
      SpytialLean.StructuralReification $indApp where
    representsAt := $(mkIdent names.representsAt)
    reifyAt_complete := $(mkIdent names.complete))

private meta structure ExposureNames where
  expose : Name
  instanceName : Name

private meta def mkExposureNames (plan : Plan) : TermElabM ExposureNames := do
  let instanceName ← mkInstName ``StructuralExposure plan.declName
  return { expose := instanceName.appendAfter "_expose", instanceName }

open TSyntax.Compat in
private meta def mkExposureBinders (plan : Plan) :
    TermElabM (Array (TSyntax ``bracketedBinder)) := do
  let mut binders := #[]
  for binder in ← mkImplicitBinders plan.argNames do
    binders := binders.push binder
  for className in #[``SpytialReify, ``StructuralReification, ``ValueIdentity,
      ``StructuralExposure] do
    for binder in ← mkInstImplicitBinders className plan.indVal plan.argNames do
      binders := binders.push binder
  let indApp ← mkInductiveApp plan.indVal plan.argNames
  binders := binders.push (← `(bracketedBinderF| [ValueIdentity $indApp]))
  return binders

private meta def mkExposureTypeKey (plan : Plan) : TermElabM Term := do
  let name ← `(IdentityKey.ofString $(quote plan.declName.toString))
  if plan.argNames.isEmpty then return name
  let arguments ← plan.argNames.mapM fun argument =>
    `(StructuralExposure.typeKey (alpha := $(mkIdent argument)))
  `(IdentityKey.ofList [$name, $arguments,*])

private meta def mkExposureCtorAlternative (plan : Plan) (names : ExposureNames)
    (constructor : CtorPlan) : TermElabM (TSyntax ``matchAlt) := do
  let mut patternArguments : Array Term := #[]
  for _ in [:constructor.numParams] do
    patternArguments := patternArguments.push (← `(_))
  let mut fields : Array Ident := #[]
  let mut exposedFields : Array Term := #[]
  let typeKey ← mkExposureTypeKey plan
  for fieldPlan in constructor.fields do
    let field := mkIdent (← mkFreshUserName `field)
    fields := fields.push field
    patternArguments := patternArguments.push field
    let child ← if fieldPlan.recursive then
      `(($(mkIdent names.expose) $field:ident).withIdentity
        $typeKey $field:ident)
    else
      `(StructuralExposure.nodeOf $field:ident)
    exposedFields := exposedFields.push
      (← `(Prod.mk $(quote fieldPlan.relation) $child:term))
  let pattern ← `(@$(mkCIdent constructor.name):ident $patternArguments:term*)
  let body ← `({
    typeName := $(quote (shortName plan.declName))
    label := $(quote constructor.label)
    fields := [$exposedFields,*]
  })
  `(matchAltExpr| | $pattern:term => $body:term)

open TSyntax.Compat in
private meta def mkExposure (plan : Plan) (names : ExposureNames) :
    TermElabM (TSyntax `command) := do
  let indApp ← mkInductiveApp plan.indVal plan.argNames
  let binders ← mkExposureBinders plan
  let value := mkIdent (← mkFreshUserName `value)
  let alternatives ← plan.ctors.mapM (mkExposureCtorAlternative plan names)
  let body ← `(match $value:ident with $alternatives:matchAlt*)
  -- Public equations let downstream losslessness derivation inspect this pattern matcher.
  -- Do not force public elaboration when a field captures a private/local identity instance:
  -- that would silently select a different field exposure from the completeness proof below.
  let canExpose ← withExporting (isExporting := false) do
    if isPrivateName plan.declName || plan.indVal.ctors.any isPrivateName then return false
    let telescope ← elabType (← `(∀ $binders:bracketedBinder*, True))
    forallTelescope telescope fun _ _ => do
      for constructor in plan.ctors do
        for field in constructor.fields do
          unless field.recursive do
            let type ← elabType field.type
            let node ← mkAppOptM ``StructuralExposure.nodeOf #[some type, none, none, none, none]
            if node.getUsedConstants.any isPrivateName then return false
      return true
  let exposureAttribute ← if canExpose then `(attr| expose) else `(attr| no_expose)
  if plan.indVal.isRec then
    `(@[$exposureAttribute:attr] def $(mkIdent names.expose):ident $binders:bracketedBinder*
        ($value:ident : $indApp) : ExposedValue := $body:term
      termination_by $value:ident)
  else
    `(@[$exposureAttribute:attr] def $(mkIdent names.expose):ident $binders:bracketedBinder*
      ($value:ident : $indApp) : ExposedValue := $body:term)

private meta def mkExposedFieldComplete (fieldPlan : FieldPlan)
    (datum fuel field inductionHypothesis : Ident) : TermElabM Term := do
  let child := mkIdent (← mkFreshUserName `child)
  let represented := mkIdent (← mkFreshUserName `represented)
  let fieldRepresented := mkIdent (← mkFreshUserName `fieldRepresented)
  let complete ← if fieldPlan.recursive then
    `(fun $child:ident $represented:ident =>
      $inductionHypothesis:ident $child:ident $field:ident $represented:ident)
  else
    `(fun $child:ident $represented:ident =>
      StructuralExposure.representsAt_of_node
        (datum := $datum:ident) (root := $child:ident) (fuel := $fuel:ident)
        (value := $field:ident) $represented:ident)
  `(fun $fieldRepresented:ident =>
    JsonDataInstance.childRepresentsWith_mono $complete:term $fieldRepresented:ident)

private meta partial def mkExposedFieldsComplete
    (constructor : CtorPlan) (fields : Array Ident)
    (datum fuel inductionHypothesis : Ident) (index : Nat := 0) : TermElabM Term := do
  let represented := mkIdent (← mkFreshUserName `represented)
  if h : index < constructor.fields.size then
    let left ← mkExposedFieldComplete constructor.fields[index] datum fuel fields[index]!
      inductionHypothesis
    let right ← mkExposedFieldsComplete constructor fields datum fuel inductionHypothesis
      (index + 1)
    `(fun $represented:ident =>
      JsonDataInstance.boolAnd_eq_true_mono $left:term $right:term $represented:ident)
  else
    `(fun _ => rfl)

private meta def mkExposureCompleteAlt
    (constructor : CtorPlan) (exposeArg representsArg : SimpArg)
    (datum fuel inductionHypothesis represented : Ident) :
    TermElabM (TSyntax ``Lean.Parser.Tactic.inductionAlt) := do
  let mut fields : Array Ident := #[]
  for _ in constructor.fields do
    fields := fields.push (mkIdent (← mkFreshUserName `field))
  let fieldsComplete ←
    mkExposedFieldsComplete constructor fields datum fuel inductionHypothesis
  let caseName := mkIdent constructor.name.getString!.toName
  `(Lean.Parser.Tactic.inductionAlt| | @$caseName:ident $fields:ident* =>
    simp only [$exposeArg, $representsArg, ExposedValue.withIdentity,
      StructuralEncoding.Node.representsAt, List.all_cons, List.all_nil]
      at $represented:ident ⊢
    exact JsonDataInstance.constructorRepresents_mono
      $fieldsComplete:term $represented:ident)

open TSyntax.Compat in
private meta def mkExposureInstance (plan : Plan) (decoderNames : DecoderNames)
    (names : ExposureNames) : TermElabM (TSyntax `command) := do
  let indApp ← mkInductiveApp plan.indVal plan.argNames
  let binders ← mkExposureBinders plan
  let value := mkIdent (← mkFreshUserName `value)
  let datum := mkIdent (← mkFreshUserName `datum)
  let root := mkIdent (← mkFreshUserName `root)
  let fuel := mkIdent (← mkFreshUserName `fuel)
  let represented := mkIdent (← mkFreshUserName `represented)
  let inductionHypothesis := mkIdent (← mkFreshUserName `inductionHypothesis)
  let currentNamespace ← getCurrNamespace
  let exposeRef := mkIdentFrom (← getRef) (currentNamespace ++ names.expose)
  let representsRef := mkIdentFrom (← getRef) (currentNamespace ++ decoderNames.representsAt)
  let exposeArg ← mkSimpArg exposeRef
  let representsArg ← mkSimpArg representsRef
  let structuralCompleteAlts ← plan.ctors.mapM fun constructor =>
    mkExposureCompleteAlt constructor exposeArg representsArg datum fuel
      inductionHypothesis represented
  let wellFormedProof ← `(by
    induction $value:ident <;>
      simp_all [$exposeArg, ExposedValue.withIdentity,
        StructuralEncoding.Node.WellFormed, StructuralEncoding.Node.FieldsWellFormed,
        StructuralExposure.nodeOf_wellFormed])
  let structuralCompleteProof ← `(by
    change $representsRef:ident $datum:ident $root:ident $fuel:ident $value:ident = true
    induction $fuel:ident generalizing $root:ident $value:ident with
    | zero =>
        simp [$exposeArg, $representsArg, ExposedValue.withIdentity,
          StructuralEncoding.Node.representsAt] at $represented:ident
    | succ $fuel:ident $inductionHypothesis:ident =>
        cases $value:ident with $structuralCompleteAlts:inductionAlt*)
  let typeKey ← mkExposureTypeKey plan
  `(instance $(mkIdent names.instanceName):ident $binders:bracketedBinder* :
      StructuralExposure $indApp where
    typeKey := $typeKey
    expose := $(mkIdent names.expose)
    wellFormed $value:ident := $wellFormedProof:term
    structuralComplete $datum:ident $root:ident $fuel:ident $value:ident $represented:ident :=
      $structuralCompleteProof:term)

/-- Derive structural reconstruction for an algebraic datatype.

The handler generates a graph decoder, an independent structural checker, their completeness proof,
and a typed exposure consumed by the shared relationalization engine. There is no second
relationalizer and no second deriving clause.

The supported declarations are regular, first-order, non-indexed inductive types and structures.
Explicit, implicit, strict-implicit, and instance-implicit data fields are reconstructed from their
relations. The field-relation names computed by the expression adapter must be pairwise distinct
within each constructor.

The generated decoder and typed exposure use exactly the constructor labels and field-relation
names emitted by the expression adapter's default constructor handling. Type parameters require
`SpytialReify` and `StructuralReification` instances, and direct regular recursion is bounded by the
datum's atom count.

Relation-name-colliding fields, dependent/indexed families, mutual and nested
recursion, and proof-, type-, or function-valued fields are rejected with a diagnostic. A type with
a custom relationalizer must provide a matching manual `SpytialReify` instance instead of deriving
this one. -/
public meta def mkSpytialReifyHandler (declNames : Array Name) : CommandElabM Bool := do
  unless declNames.size > 0 do return false
  let env ← getEnv
  unless declNames.all fun name => (env.find? name) matches some (.inductInfo _) do return false
  for declName in declNames do
    withoutExposeFromCtors declName do
      let plan ← liftTermElabM <| mkPlan declName
      let decoderNames ← liftTermElabM <| mkNames plan
      let exposureNames ← liftTermElabM <| mkExposureNames plan
      elabCommand (← liftTermElabM <| mkDecoder plan decoderNames)
      elabCommand (← liftTermElabM <| mkInstance plan decoderNames)
      elabCommand (← liftTermElabM <| mkRepresentsAt plan decoderNames)
      elabCommand (← liftTermElabM <| mkComplete plan decoderNames)
      elabCommand (← liftTermElabM <| mkStructuralInstance plan decoderNames)
      elabCommand (← liftTermElabM <| mkExposure plan exposureNames)
      elabCommand (← liftTermElabM <| mkExposureInstance plan decoderNames exposureNames)
      let checkerName := (← getCurrNamespace) ++ decoderNames.representsAt
      modifyEnv (derivedRepresentsExt.addEntry · (declName, checkerName))
  return true

meta initialize
  registerDerivingHandler ``SpytialReify mkSpytialReifyHandler

end SpytialLean.SpytialReify.Deriving
