/-
GENERATED by `lake exe sgqCodegen` (just gen-sgq) from simple-graph-query
3.1.0's docs/sgq-language.json. Do not edit; edit the generator instead.

These are the engine's own lexical and grammatical facts, not this package's
choices: what a bare name may contain, what has to be quoted, how each
operator is spelled, and where each sits in the precedence cascade.
-/
module

namespace SpytialLean.Sgq

/-- Where a construct sits in the cascade, and the level each of its operand
    slots descends to. A subexpression needs parentheses exactly when its own
    `prec` is below the level of the slot it fills -- which is not always the
    neighbouring level, so these are read rather than assumed. -/
public meta structure Op where
  text : String
  prec : Nat
  operands : List Nat
  deriving Repr, Inhabited

/-- The level of the loosest expression: what a delimiter accepts inside it. -/
public meta def loosest : Nat := 0

/-! ## Operators -/

/-- `let` — let, from the let construct. -/
public meta def «let» : Op :=
  { text := "let", prec := 0, operands := [] }
/-- `bind` — bind, from the bind construct. -/
public meta def «bind» : Op :=
  { text := "bind", prec := 0, operands := [] }
/-- `all` — all, from the quantifier construct. -/
public meta def «all» : Op :=
  { text := "all", prec := 0, operands := [] }
/-- `no` — no, from the quantifier construct. -/
public meta def «no» : Op :=
  { text := "no", prec := 0, operands := [] }
/-- `sum` — sum, from the quantifier construct. -/
public meta def «sum» : Op :=
  { text := "sum", prec := 0, operands := [] }
/-- `lone` — lone, from the quantifier construct. -/
public meta def «lone» : Op :=
  { text := "lone", prec := 0, operands := [] }
/-- `some` — some, from the quantifier construct. -/
public meta def «some» : Op :=
  { text := "some", prec := 0, operands := [] }
/-- `one` — one, from the quantifier construct. -/
public meta def «one» : Op :=
  { text := "one", prec := 0, operands := [] }
/-- `two` — two, from the quantifier construct. -/
public meta def «two» : Op :=
  { text := "two", prec := 0, operands := [] }
/-- `or` — or, from the or construct. -/
public meta def «or» : Op :=
  { text := "or", prec := 1, operands := [1, 2] }
/-- `xor` — xor, from the xor construct. -/
public meta def «xor» : Op :=
  { text := "xor", prec := 2, operands := [2, 3] }
/-- `iff` — iff, from the iff construct. -/
public meta def «iff» : Op :=
  { text := "iff", prec := 3, operands := [3, 4] }
/-- `implies` — implies, from the implies construct. -/
public meta def «implies» : Op :=
  { text := "implies", prec := 4, operands := [5, 4, 4] }
/-- `and` — and, from the and construct. -/
public meta def «and» : Op :=
  { text := "and", prec := 5, operands := [5, 6] }
/-- `not` — not, from the not construct. -/
public meta def «not» : Op :=
  { text := "not", prec := 6, operands := [6] }
/-- `in` — subset, from the comparison construct. -/
public meta def «subset» : Op :=
  { text := "in", prec := 7, operands := [7, 8] }
/-- `=` — equal, from the comparison construct. -/
public meta def «equal» : Op :=
  { text := "=", prec := 7, operands := [7, 8] }
/-- `<` — lessThan, from the comparison construct. -/
public meta def «lessThan» : Op :=
  { text := "<", prec := 7, operands := [7, 8] }
/-- `>` — greaterThan, from the comparison construct. -/
public meta def «greaterThan» : Op :=
  { text := ">", prec := 7, operands := [7, 8] }
/-- `<=` — atMost, from the comparison construct. -/
public meta def «atMost» : Op :=
  { text := "<=", prec := 7, operands := [7, 8] }
/-- `>=` — atLeast, from the comparison construct. -/
public meta def «atLeast» : Op :=
  { text := ">=", prec := 7, operands := [7, 8] }
/-- `ni` — contains, from the comparison construct. -/
public meta def «contains» : Op :=
  { text := "ni", prec := 7, operands := [7, 8] }
/-- `is` — is, from the comparison construct. -/
public meta def «is» : Op :=
  { text := "is", prec := 7, operands := [7, 8] }
/-- `no` — empty, from the multiplicityTest construct. -/
public meta def «empty» : Op :=
  { text := "no", prec := 8, operands := [9] }
/-- `some` — nonEmpty, from the multiplicityTest construct. -/
public meta def «nonEmpty» : Op :=
  { text := "some", prec := 8, operands := [9] }
/-- `lone` — atMostOne, from the multiplicityTest construct. -/
public meta def «atMostOne» : Op :=
  { text := "lone", prec := 8, operands := [9] }
/-- `one` — exactlyOne, from the multiplicityTest construct. -/
public meta def «exactlyOne» : Op :=
  { text := "one", prec := 8, operands := [9] }
/-- `two` — exactlyTwo, from the multiplicityTest construct. -/
public meta def «exactlyTwo» : Op :=
  { text := "two", prec := 8, operands := [9] }
/-- `set` — any, from the multiplicityTest construct. -/
public meta def «any» : Op :=
  { text := "set", prec := 8, operands := [9] }
/-- `+` — union, from the unionDifference construct. -/
public meta def «union» : Op :=
  { text := "+", prec := 9, operands := [9, 11] }
/-- `-` — difference, from the unionDifference construct. -/
public meta def «difference» : Op :=
  { text := "-", prec := 9, operands := [9, 11] }
/-- `#` — cardinality, from the cardinality construct. -/
public meta def «cardinality» : Op :=
  { text := "#", prec := 10, operands := [10] }
/-- `++` — override, from the override construct. -/
public meta def «override» : Op :=
  { text := "++", prec := 11, operands := [11, 12] }
/-- `&` — intersection, from the intersection construct. -/
public meta def «intersection» : Op :=
  { text := "&", prec := 12, operands := [12, 13] }
/-- `->` — product, from the product construct. -/
public meta def «product» : Op :=
  { text := "->", prec := 13, operands := [13, 14] }
/-- `<:` — domainRestriction, from the restriction construct. -/
public meta def «domainRestriction» : Op :=
  { text := "<:", prec := 14, operands := [14, 15] }
/-- `:>` — rangeRestriction, from the restriction construct. -/
public meta def «rangeRestriction» : Op :=
  { text := ":>", prec := 14, operands := [14, 15] }
/-- `.` — join, from the join construct. -/
public meta def «join» : Op :=
  { text := ".", prec := 16, operands := [16, 17] }
/-- `~` — transpose, from the unaryPrefix construct. -/
public meta def «transpose» : Op :=
  { text := "~", prec := 17, operands := [17] }
/-- `^` — transitiveClosure, from the unaryPrefix construct. -/
public meta def «transitiveClosure» : Op :=
  { text := "^", prec := 17, operands := [17] }
/-- `*` — reflexiveTransitiveClosure, from the unaryPrefix construct. -/
public meta def «reflexiveTransitiveClosure» : Op :=
  { text := "*", prec := 17, operands := [17] }
/-- `@:` — label, from the unaryPrefix construct. -/
public meta def «label» : Op :=
  { text := "@:", prec := 17, operands := [17] }
/-- `@str:` — labelString, from the unaryPrefix construct. -/
public meta def «labelString» : Op :=
  { text := "@str:", prec := 17, operands := [17] }
/-- `@bool:` — labelBoolean, from the unaryPrefix construct. -/
public meta def «labelBoolean» : Op :=
  { text := "@bool:", prec := 17, operands := [17] }
/-- `@num:` — labelNumber, from the unaryPrefix construct. -/
public meta def «labelNumber» : Op :=
  { text := "@num:", prec := 17, operands := [17] }
/-- `none` — emptySet, from the constant construct. -/
public meta def «emptySet» : Op :=
  { text := "none", prec := 18, operands := [] }
/-- `univ` — universe, from the constant construct. -/
public meta def «universe» : Op :=
  { text := "univ", prec := 18, operands := [] }
/-- `iden` — identity, from the constant construct. -/
public meta def «identity» : Op :=
  { text := "iden", prec := 18, operands := [] }
/-- `@` — atName, from the atName construct. -/
public meta def «atName» : Op :=
  { text := "@", prec := 18, operands := [] }
/-- ``` — atomLiteral, from the atomLiteral construct. -/
public meta def «atomLiteral» : Op :=
  { text := "`", prec := 18, operands := [] }
/-- `this` — this, from the this construct. -/
public meta def «this» : Op :=
  { text := "this", prec := 18, operands := [] }
/-- `sexpr` — sexpr, from the sexpr construct. -/
public meta def «sexpr» : Op :=
  { text := "sexpr", prec := 18, operands := [] }

/-! ## Fixed syntax -/

/-- The bar of a let. -/
public meta def «let».«bar» : String := "|"
/-- The bind of a let. -/
public meta def «let».«bind» : String := "="
/-- The blockClose of a let. -/
public meta def «let».«blockClose» : String := "}"
/-- The blockOpen of a let. -/
public meta def «let».«blockOpen» : String := "{"
/-- The separator of a let. -/
public meta def «let».«separator» : String := ","
/-- The bar of a bind. -/
public meta def «bind».«bar» : String := "|"
/-- The bind of a bind. -/
public meta def «bind».«bind» : String := "="
/-- The blockClose of a bind. -/
public meta def «bind».«blockClose» : String := "}"
/-- The blockOpen of a bind. -/
public meta def «bind».«blockOpen» : String := "{"
/-- The separator of a bind. -/
public meta def «bind».«separator» : String := ","
/-- The bar of a quantifier. -/
public meta def «quantifier».«bar» : String := "|"
/-- The blockClose of a quantifier. -/
public meta def «quantifier».«blockClose» : String := "}"
/-- The blockOpen of a quantifier. -/
public meta def «quantifier».«blockOpen» : String := "{"
/-- The colon of a quantifier. -/
public meta def «quantifier».«colon» : String := ":"
/-- The disjoint of a quantifier. -/
public meta def «quantifier».«disjoint» : String := "disj"
/-- The domainMultiplicity of a quantifier. -/
public meta def «quantifier».«domainMultiplicity» : String := "set"
/-- The separator of a quantifier. -/
public meta def «quantifier».«separator» : String := ","
/-- The else of a implies. -/
public meta def «implies».«else» : String := "else"
/-- The negation of a comparison. -/
public meta def «comparison».«negation» : String := "!"
/-- The close of a application. -/
public meta def «application».«close» : String := "]"
/-- The open of a application. -/
public meta def «application».«open» : String := "["
/-- The separator of a application. -/
public meta def «application».«separator» : String := ","
/-- The close of a appliedName. -/
public meta def «appliedName».«close» : String := "]"
/-- The open of a appliedName. -/
public meta def «appliedName».«open» : String := "["
/-- The separator of a appliedName. -/
public meta def «appliedName».«separator» : String := ","
/-- The negation of a constant. -/
public meta def «constant».«negation» : String := "-"
/-- The bar of a comprehension. -/
public meta def «comprehension».«bar» : String := "|"
/-- The close of a comprehension. -/
public meta def «comprehension».«close» : String := "}"
/-- The colon of a comprehension. -/
public meta def «comprehension».«colon» : String := ":"
/-- The disjoint of a comprehension. -/
public meta def «comprehension».«disjoint» : String := "disj"
/-- The domainMultiplicity of a comprehension. -/
public meta def «comprehension».«domainMultiplicity» : String := "set"
/-- The open of a comprehension. -/
public meta def «comprehension».«open» : String := "{"
/-- The separator of a comprehension. -/
public meta def «comprehension».«separator» : String := ","
/-- The close of a grouping. -/
public meta def «grouping».«close» : String := ")"
/-- The open of a grouping. -/
public meta def «grouping».«open» : String := "("
/-- The close of a block. -/
public meta def «block».«close» : String := "}"
/-- The open of a block. -/
public meta def «block».«open» : String := "{"
/-- The multiplicity spellings a product chooses between. -/
public meta def «product».«multiplicity» : List String := ["lone", "some", "one", "two", "set"]

/-! ## Names -/

/-- Spellings a bare identifier cannot carry: they lex as some other token. -/
public meta def reserved : List String :=
  ["/", "Int", "abstract", "all", "and", "as", "assert", "bind", "but", "check", "checked", "consistent", "disj", "else", "eval", "exactly", "example", "expect", "extends", "for", "forge_error", "fun", "func", "iden", "iff", "implies", "in", "inconsistent", "inst", "is", "let", "lone", "necessary", "ni", "no", "none", "not", "one", "open", "option", "or", "pfunc", "pred", "run", "sat", "set", "sexpr", "sig", "some", "sufficient", "suite", "sum", "test", "theorem", "this", "two", "univ", "unsat", "var", "wheat", "with", "xor"]

public meta def bareHead (c : Char) : Bool := ('a' ≤ c && c ≤ 'z') || ('A' ≤ c && c ≤ 'Z') || c == '_' || c == '$' || c == '/'

public meta def bareRest (c : Char) : Bool := ('a' ≤ c && c ≤ 'z') || ('A' ≤ c && c ≤ 'Z') || ('0' ≤ c && c ≤ '9') || c == '_' || c == '$' || c == '/'

public meta def bareMinLength : Nat := 1

public meta def quoteDelimiter : Char := '`'
public meta def quoteEscape : Char := '\\'
/-- Characters the quoted form refuses raw, so an encoder must escape them. -/
public meta def quoteMustEscape : List Char := ['`', '\\']
/-- The shortest name the quoted form can spell; the empty name has no spelling at all. -/
public meta def quoteMinLength : Nat := 1

/-! ## String literals -/

public meta def stringDelimiter : Char := '"'
public meta def stringEscape : Char := '\\'
public meta def stringMustEscape : List Char := ['"', '\\']

/-- Readable spellings for characters that would otherwise ride raw. The
    engine resolves these; anything else after the escape denotes itself. -/
public meta def stringEscapeSpelling : Char → Option Char
  | Char.ofNat 0 => Option.some '0'
  | '\n' => Option.some 'n'
  | '\r' => Option.some 'r'
  | '\t' => Option.some 't'
  | _ => none

/-! ## Builtins -/

public meta def binaryBuiltins : List String := ["add", "subtract", "multiply", "divide", "remainder"]
public meta def unaryBuiltins : List String := ["abs", "sign", "floor", "ceil"]
/-- Aggregators: they fold a set to a number. -/
public meta def setBuiltins : List String := ["min", "max", "sum"]

end SpytialLean.Sgq
