/-
@generated by `lake exe specCodegen` — do not edit by hand.

Source: spytial-core 5.0.0, layout-spec language 2026-07-29
        (widget/node_modules/spytial-core/docs/spytial-language.json,
        pinned by widget/pnpm-lock.yaml to the same release as the
        embedded renderer)
Regenerate: just gen-spec        Drift check: just check-spec

Optional fields default to unset and are omitted from the emitted YAML, so
spytial-core's own defaults apply. Enum parameters with a manifest default
bake it as a Lean default argument and always emit, so the traversal order
or edge direction is stated at the authoring site.
-/
module

public import Lean

namespace SpytialLean

/-- The spytial-core release this surface was generated from. -/
public meta def specCoreVersion : String := "5.0.0"

/-- The date the layout-spec language last changed, per the manifest. -/
public meta def specLanguageVersion : String := "2026-07-29"

/-- Closed vocabulary for `textStyle.size`. -/
public meta inductive TextSize where
  | small | normal | large
  deriving Repr, DecidableEq, Inhabited

private meta def TextSize.toYamlStr : TextSize → String
  | .small => "small"
  | .normal => "normal"
  | .large => "large"

/-- Closed vocabulary for `lineStyle.pattern`, `inferredEdge.style`, `edgeColor.style`. -/
public meta inductive LinePattern where
  | solid | dashed | dotted
  deriving Repr, DecidableEq, Inhabited

private meta def LinePattern.toYamlStr : LinePattern → String
  | .solid => "solid"
  | .dashed => "dashed"
  | .dotted => "dotted"

/-- Closed vocabulary for `iconStyle.placement`. -/
public meta inductive IconPlacement where
  | full | badge
  deriving Repr, DecidableEq, Inhabited

private meta def IconPlacement.toYamlStr : IconPlacement → String
  | .full => "full"
  | .badge => "badge"

/-- Closed vocabulary for `orientation.directions`. -/
public meta inductive Direction where
  | above | below | left | right | directlyAbove | directlyBelow | directlyLeft | directlyRight
  deriving Repr, DecidableEq, Inhabited

private meta def Direction.toYamlStr : Direction → String
  | .above => "above"
  | .below => "below"
  | .left => "left"
  | .right => "right"
  | .directlyAbove => "directlyAbove"
  | .directlyBelow => "directlyBelow"
  | .directlyLeft => "directlyLeft"
  | .directlyRight => "directlyRight"

/-- Closed vocabulary for `cyclic.direction`. -/
public meta inductive RotationDir where
  | clockwise | counterclockwise
  deriving Repr, DecidableEq, Inhabited

private meta def RotationDir.toYamlStr : RotationDir → String
  | .clockwise => "clockwise"
  | .counterclockwise => "counterclockwise"

/-- Closed vocabulary for `align.direction`. -/
public meta inductive AlignDir where
  | horizontal | vertical
  deriving Repr, DecidableEq, Inhabited

private meta def AlignDir.toYamlStr : AlignDir → String
  | .horizontal => "horizontal"
  | .vertical => "vertical"

/-- Closed vocabulary for `group.addEdge`. -/
public meta inductive GroupEdge where
  | none | toGroup | fromGroup
  deriving Repr, DecidableEq, Inhabited

private meta def GroupEdge.toYamlStr : GroupEdge → String
  | .none => "none"
  | .toGroup => "togroup"
  | .fromGroup => "fromgroup"

/-- Closed vocabulary for `flag.flag`. -/
public meta inductive FlagName where
  | hideDisconnected | hideDisconnectedBuiltIns
  deriving Repr, DecidableEq, Inhabited

private meta def FlagName.toYamlStr : FlagName → String
  | .hideDisconnected => "hideDisconnected"
  | .hideDisconnectedBuiltIns => "hideDisconnectedBuiltIns"

/-- `hold: never` negates a constraint: it asserts the relationship must not hold. Only the value `never` has an effect — `always`, any other string, and an absent field all mean the positive constraint. Double negation is not supported. `size` and `hideAtom` accept the key syntactically but ignore it. -/
public meta inductive Hold where
  | always | never
  deriving Repr, DecidableEq, Inhabited

/-! ## YAML emission helpers

Each op serializes to one flow-style YAML list item, e.g.
`  - orientation: {selector: "edges", directions: [above]}`.
Strings are JSON-escaped (JSON is a subset of YAML flow style). -/

private meta def escStr (s : String) : String := (Lean.Json.str s).compress

private meta def kv (k v : String) : String := k ++ ": " ++ v

private meta def flow (cells : List String) : String :=
  "{" ++ String.intercalate ", " cells ++ "}"

private meta def yamlList (vs : List String) : String :=
  "[" ++ String.intercalate ", " vs ++ "]"

private meta def opt {α : Type} (k : String) (f : α → String) : Option α → List String
  | some v => [kv k (f v)]
  | none => []

private meta def blockField (k : String) (cells : List String) : List String :=
  if cells.isEmpty then [] else [kv k (flow cells)]

private meta def holdFields : Hold → List String
  | .never => [kv "hold" "never"]
  | .always => []

/-- Render a positive float without the noise `toString` appends (`2.000000`). -/
private meta def fmtFloat (f : Float) : String :=
  let s := toString f
  if s.contains '.' then
    let cs := s.toList.reverse.dropWhile (· == '0')
    let cs := if cs.head? == some '.' then cs.drop 1 else cs
    String.ofList cs.reverse
  else s

/-- Styling for a label. Reused by every form that renders text — an atom's own label, attribute and tag lines, edge labels, and a group label. -/
public meta structure TextStyle where
  /-- Font-size tier relative to the node label: `large` renders bigger than the label, `normal` smaller, `small` smaller still. -/
  size : Option TextSize := none
  /-- Any CSS color. Unset inherits the node label color, so dark mode still adapts. -/
  color : Option String := none
  deriving Repr, Inhabited

private meta def TextStyle.yamlFields (b : TextStyle) : List String :=
  opt "size" TextSize.toYamlStr b.size ++ opt "color" escStr b.color

/-- Styling for an edge's drawn line. Reused by edgeStyle, inferredEdge, and a group's addEdge connector. -/
public meta structure LineStyle where
  /-- Any CSS color. -/
  color : Option String := none
  /-- Dash pattern of the line. -/
  pattern : Option LinePattern := none
  /-- Line thickness in pixels. Must be > 0; a non-positive or non-numeric weight is dropped. -/
  weight : Option Float := none
  /-- A wider, translucent underlay drawn beneath the line. Orthogonal to color and pattern. -/
  highlight : Option String := none
  deriving Repr, Inhabited

private meta def LineStyle.yamlFields (b : LineStyle) : List String :=
  opt "color" escStr b.color ++ opt "pattern" LinePattern.toYamlStr b.pattern ++ opt "weight" fmtFloat b.weight ++ opt "highlight" escStr b.highlight

private meta def LineStyle.validate (b : LineStyle) : List String :=
  (match b.weight with | some v => (if v <= 0 then ["lineStyle.weight must be > 0"] else []) | none => [])

/-- An atom's interior fill. Opt-in: the default look is unfilled, with only the border and label marking the node. -/
public meta structure FillStyle where
  /-- Any CSS color. -/
  color : Option String := none
  deriving Repr, Inhabited

private meta def FillStyle.yamlFields (b : FillStyle) : List String :=
  opt "color" escStr b.color

/-- An atom's outline. -/
public meta structure BorderStyle where
  /-- Any CSS color. -/
  color : Option String := none
  /-- Outline thickness in pixels. Must be > 0; anything else is dropped. -/
  width : Option Float := none
  deriving Repr, Inhabited

private meta def BorderStyle.yamlFields (b : BorderStyle) : List String :=
  opt "color" escStr b.color ++ opt "width" fmtFloat b.width

private meta def BorderStyle.validate (b : BorderStyle) : List String :=
  (match b.width with | some v => (if v <= 0 then ["borderStyle.width must be > 0"] else []) | none => [])

/-- An icon drawn on an atom. Every leaf is optional, including `path`, so a supertype rule can supply the icon and a subtype rule tune only its opacity. -/
public meta structure IconStyle where
  /-- A bundled icon name (`person`), an icon-pack reference (`bi:person-fill`), a URL, or a path. Resolved to a concrete URL or data URI at parse time. An iconStyle with no path draws nothing. -/
  path : Option String := none
  /-- `full` — the icon occupies the box, which stays transparent unless a fillStyle.color is given. `badge` — a small marker in the top-right corner, secondary to the label. -/
  placement : Option IconPlacement := none
  /-- Alpha in [0,1]. Out-of-range values are dropped rather than clamped. Fade a `full` icon to use it as a watermark behind the label. -/
  opacity : Option Float := none
  deriving Repr, Inhabited

private meta def IconStyle.yamlFields (b : IconStyle) : List String :=
  opt "path" escStr b.path ++ opt "placement" IconPlacement.toYamlStr b.placement ++ opt "opacity" fmtFloat b.opacity

private meta def IconStyle.validate (b : IconStyle) : List String :=
  (match b.opacity with | some v => (if v < 0 then ["iconStyle.opacity must be >= 0"] else []) ++ (if v > 1 then ["iconStyle.opacity must be <= 1"] else []) | none => [])

/-- A single Spytial operation — either a constraint (structural layout) or a
    directive (presentation). Generated from spytial-core's language manifest;
    one constructor per form the layout-spec parser reads. -/
public meta inductive SpytialOp where
  /-- Place the two ends of each selected tuple relative to one another. -/
  | orientation (selector : String) (directions : List Direction) (hold : Hold := .always)
  /-- Arrange the selected atoms around the perimeter of a circle, in the order the selector defines. -/
  | cyclic (selector : String) (direction : RotationDir := .clockwise) (hold : Hold := .always)
  /-- Put the selected atoms on a shared horizontal or vertical line. -/
  | align (selector : String) (direction : AlignDir) (hold : Hold := .always)
  /-- Draw a hull around a set of atoms. For tuples (a, b), (a, c), … the group is keyed by `a` and contains {b, c, …}. -/
  | group (selector : String) (name : String) (addEdge : GroupEdge := .none) (textStyle : TextStyle := {}) (hold : Hold := .always)
  /-- Group by indexing into the tuples of a relation. **Deprecated:** `group.byField` is deprecated — use `group`. A binary selector whose first column is the key and whose second is the members says the same thing without tuple indices. -/
  | groupByField (field : String) (groupOn : Nat) (addToGroup : Nat) (selector : Option String := none) (hold : Hold := .always)
  /-- Set the width and height of matching nodes, in pixels. -/
  | size (width : Nat) (height : Nat) (selector : Option String := none)
  /-- Remove matching atoms from the diagram. -/
  | hideAtom (selector : String)
  /-- Toggle a whole-diagram rendering behaviour. -/
  | flag (name : FlagName)
  /-- Style matching atoms. An atom is a composite of an interior fill, an outline, an icon, and its label, so each is its own block. -/
  | atomStyle (selector : Option String := none) (fillStyle : FillStyle := {}) (borderStyle : BorderStyle := {}) (iconStyle : IconStyle := {}) (textStyle : TextStyle := {}) (showLabel : Option Bool := none)
  /-- Style the edges of a relation: the drawn line, the label, and visibility. -/
  | edgeStyle (field : String) (selector : Option String := none) (filter : Option String := none) (lineStyle : LineStyle := {}) (textStyle : TextStyle := {}) (showLabel : Option Bool := none) (hidden : Option Bool := none)
  /-- Render a relation as a key-value line on its source node instead of as an edge. -/
  | attribute (field : String) (selector : Option String := none) (filter : Option String := none) (textStyle : TextStyle := {})
  /-- Add a computed key-value line to matching nodes, without touching the graph structure. -/
  | tag (toTag : String) (name : String) (value : String) (textStyle : TextStyle := {})
  /-- Hide a relation's edges. -/
  | hideField (field : String) (selector : Option String := none) (filter : Option String := none)
  /-- Draw an edge that is not in the data, computed from a selector. -/
  | inferredEdge (name : String) (selector : String) (draw : Option String := none) (lineStyle : LineStyle := {}) (textStyle : TextStyle := {}) (color : Option String := none) (style : Option LinePattern := none) (weight : Option Float := none) (highlight : Option String := none)
  /-- Assign an icon to matching atoms. **Deprecated:** `icon` is deprecated — use `atomStyle`. The single `showLabels` boolean drove label visibility and icon geometry at once. atomStyle splits those into two independent knobs, which is what makes a faded watermark, or a hidden label with no icon, expressible. -/
  | icon (selector : String) (path : String) (showLabels : Option Bool := none)
  /-- Set the color of matching atoms. **Deprecated:** `atomColor` is deprecated — use `atomStyle`. atomStyle expresses the same recolor and also reaches the fill, the icon, and the label. The rewrite is border-preserving, so an existing diagram is unchanged. -/
  | atomColor (value : String) (selector : String)
  /-- Style a relation's edges with flat, inline keys. **Deprecated:** `edgeColor` is deprecated — use `edgeStyle`. edgeStyle groups the same knobs into the shared lineStyle/textStyle blocks that every other form uses. -/
  | edgeColor (field : String) (value : String) (selector : Option String := none) (filter : Option String := none) (style : Option LinePattern := none) (weight : Option Float := none) (highlight : Option String := none) (showLabel : Option Bool := none) (hidden : Option Bool := none)
  deriving Repr, Inhabited

/-- Is this op a constraint (emitted under `constraints:`)? `size` and
    `hideAtom` are constraints; their old placement under `directives` is
    deprecated upstream and never emitted here. -/
public meta def SpytialOp.isConstraint : SpytialOp → Bool
  | .orientation .. | .cyclic .. | .align .. | .group .. | .groupByField .. | .size .. | .hideAtom .. => true
  | _ => false

/-- Render one op as a YAML list item (a single line, flow style). -/
public meta def SpytialOp.toYamlLine : SpytialOp → String
  | .orientation selector directions hold =>
    "  - orientation: " ++ flow ([kv "selector" (escStr selector)] ++ [kv "directions" (yamlList (directions.map Direction.toYamlStr))] ++ holdFields hold)
  | .cyclic selector direction hold =>
    "  - cyclic: " ++ flow ([kv "selector" (escStr selector)] ++ [kv "direction" direction.toYamlStr] ++ holdFields hold)
  | .align selector direction hold =>
    "  - align: " ++ flow ([kv "selector" (escStr selector)] ++ [kv "direction" direction.toYamlStr] ++ holdFields hold)
  | .group selector name addEdge textStyle hold =>
    "  - group: " ++ flow ([kv "selector" (escStr selector)] ++ [kv "name" (escStr name)] ++ [kv "addEdge" addEdge.toYamlStr] ++ blockField "textStyle" textStyle.yamlFields ++ holdFields hold)
  | .groupByField field groupOn addToGroup selector hold =>
    "  - group: " ++ flow ([kv "field" (escStr field)] ++ [kv "groupOn" (toString groupOn)] ++ [kv "addToGroup" (toString addToGroup)] ++ opt "selector" escStr selector ++ holdFields hold)
  | .size width height selector =>
    "  - size: " ++ flow ([kv "width" (toString width)] ++ [kv "height" (toString height)] ++ opt "selector" escStr selector)
  | .hideAtom selector =>
    "  - hideAtom: " ++ flow ([kv "selector" (escStr selector)])
  | .flag name => "  - flag: " ++ name.toYamlStr
  | .atomStyle selector fillStyle borderStyle iconStyle textStyle showLabel =>
    "  - atomStyle: " ++ flow (opt "selector" escStr selector ++ blockField "fillStyle" fillStyle.yamlFields ++ blockField "borderStyle" borderStyle.yamlFields ++ blockField "iconStyle" iconStyle.yamlFields ++ blockField "textStyle" textStyle.yamlFields ++ opt "showLabel" toString showLabel)
  | .edgeStyle field selector filter lineStyle textStyle showLabel hidden =>
    "  - edgeStyle: " ++ flow ([kv "field" (escStr field)] ++ opt "selector" escStr selector ++ opt "filter" escStr filter ++ blockField "lineStyle" lineStyle.yamlFields ++ blockField "textStyle" textStyle.yamlFields ++ opt "showLabel" toString showLabel ++ opt "hidden" toString hidden)
  | .attribute field selector filter textStyle =>
    "  - attribute: " ++ flow ([kv "field" (escStr field)] ++ opt "selector" escStr selector ++ opt "filter" escStr filter ++ blockField "textStyle" textStyle.yamlFields)
  | .tag toTag name value textStyle =>
    "  - tag: " ++ flow ([kv "toTag" (escStr toTag)] ++ [kv "name" (escStr name)] ++ [kv "value" (escStr value)] ++ blockField "textStyle" textStyle.yamlFields)
  | .hideField field selector filter =>
    "  - hideField: " ++ flow ([kv "field" (escStr field)] ++ opt "selector" escStr selector ++ opt "filter" escStr filter)
  | .inferredEdge name selector draw lineStyle textStyle color style weight highlight =>
    "  - inferredEdge: " ++ flow ([kv "name" (escStr name)] ++ [kv "selector" (escStr selector)] ++ opt "draw" escStr draw ++ blockField "lineStyle" lineStyle.yamlFields ++ blockField "textStyle" textStyle.yamlFields ++ opt "color" escStr color ++ opt "style" LinePattern.toYamlStr style ++ opt "weight" fmtFloat weight ++ opt "highlight" escStr highlight)
  | .icon selector path showLabels =>
    "  - icon: " ++ flow ([kv "selector" (escStr selector)] ++ [kv "path" (escStr path)] ++ opt "showLabels" toString showLabels)
  | .atomColor value selector =>
    "  - atomColor: " ++ flow ([kv "value" (escStr value)] ++ [kv "selector" (escStr selector)])
  | .edgeColor field value selector filter style weight highlight showLabel hidden =>
    "  - edgeColor: " ++ flow ([kv "field" (escStr field)] ++ [kv "value" (escStr value)] ++ opt "selector" escStr selector ++ opt "filter" escStr filter ++ opt "style" LinePattern.toYamlStr style ++ opt "weight" fmtFloat weight ++ opt "highlight" escStr highlight ++ opt "showLabel" toString showLabel ++ opt "hidden" toString hidden)

/-- Author-time checks the manifest states outright: numeric bounds and
    `orientation`'s mutually-exclusive direction rules. spytial-core mostly
    does *not* complain about these — an out-of-range leaf is dropped
    silently — so elaboration is where they can fail loudly. -/
public meta def SpytialOp.validate : SpytialOp → List String
  | .orientation _ directions _ =>
    (if (([Direction.above, Direction.below] : List Direction).filter (directions.contains ·)).length > 1 then ["orientation: directions may contain at most one of 'above'/'below'"] else []) ++ (if (([Direction.left, Direction.right] : List Direction).filter (directions.contains ·)).length > 1 then ["orientation: directions may contain at most one of 'left'/'right'"] else []) ++ (if directions.contains .directlyAbove && !directions.all (fun d => ([Direction.above, Direction.directlyAbove] : List Direction).contains d) then ["orientation: 'directlyAbove' may only be combined with 'above'/'directlyAbove'"] else []) ++ (if directions.contains .directlyBelow && !directions.all (fun d => ([Direction.below, Direction.directlyBelow] : List Direction).contains d) then ["orientation: 'directlyBelow' may only be combined with 'below'/'directlyBelow'"] else []) ++ (if directions.contains .directlyLeft && !directions.all (fun d => ([Direction.left, Direction.directlyLeft] : List Direction).contains d) then ["orientation: 'directlyLeft' may only be combined with 'left'/'directlyLeft'"] else []) ++ (if directions.contains .directlyRight && !directions.all (fun d => ([Direction.right, Direction.directlyRight] : List Direction).contains d) then ["orientation: 'directlyRight' may only be combined with 'right'/'directlyRight'"] else [])
  | .size width height _ =>
    (let v := Float.ofNat width; (if v <= 0 then ["size: width must be > 0"] else [])) ++ (let v := Float.ofNat height; (if v <= 0 then ["size: height must be > 0"] else []))
  | .atomStyle _ _ borderStyle iconStyle _ _ =>
    borderStyle.validate ++ iconStyle.validate
  | .edgeStyle _ _ _ lineStyle _ _ _ =>
    lineStyle.validate
  | .inferredEdge _ _ _ lineStyle _ _ _ weight _ =>
    lineStyle.validate ++ (match weight with | some v => (if v <= 0 then ["inferredEdge: weight must be > 0"] else []) | none => [])
  | .edgeColor _ _ _ _ _ weight _ _ _ =>
    (match weight with | some v => (if v <= 0 then ["edgeColor: weight must be > 0"] else []) | none => [])
  | _ => []

/-- A warning when the op (or a field it sets) is a form spytial-core has
    deprecated. Deprecated forms keep parsing and keep their meaning; they are
    removed only in a major release of spytial-core. -/
public meta def SpytialOp.deprecationWarning : SpytialOp → Option String
  | .groupByField .. => some "`group.byField` is deprecated — use `group`. A binary selector whose first column is the key and whose second is the members says the same thing without tuple indices."
  | .icon .. => some "`icon` is deprecated — use `atomStyle`. The single `showLabels` boolean drove label visibility and icon geometry at once. atomStyle splits those into two independent knobs, which is what makes a faded watermark, or a hidden label with no icon, expressible."
  | .atomColor .. => some "`atomColor` is deprecated — use `atomStyle`. atomStyle expresses the same recolor and also reaches the fill, the icon, and the label. The rewrite is border-preserving, so an existing diagram is unchanged."
  | .edgeColor .. => some "`edgeColor` is deprecated — use `edgeStyle`. edgeStyle groups the same knobs into the shared lineStyle/textStyle blocks that every other form uses."
  | .inferredEdge _ _ _ _ _ color style weight highlight =>
    if color.isSome || style.isSome || weight.isSome || highlight.isSome then some "inferredEdge: flat style fields are deprecated (color -> inferredEdge.lineStyle.color, style -> inferredEdge.lineStyle.pattern, weight -> inferredEdge.lineStyle.weight, highlight -> inferredEdge.lineStyle.highlight)" else none
  | _ => none

end SpytialLean
